In [ ]:
!pip install tensorflow==2.15.0 tensorflow-hub keras==2.15.0

INFO: pip is looking at multiple versions of tf-keras to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 475.2/475.2 MB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 21.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 35.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 30.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.0/442.0 kB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 38.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 6.8 MB/s eta 0:00:00
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.16.0
    Uninstalling wrapt-1.16.0:
      Successfully uninstalled wrapt-1.16.0
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.4.1
    Uninstalling ml-dtypes-0.4.1:
      Successfully uninstalled ml-dtypes

In [ ]:
!nvidia-smi

Tue Sep 24 14:38:54 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import os

if not os.path.exists("helper_functions.py"):
    !wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
else:
    print("[INFO] 'helper_functions.py' already exists, skipping download.")

--2024-09-24 14:38:54--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2024-09-24 14:38:54 (111 MB/s) - ‘helper_functions.py’ saved [10246/10246]



In [ ]:
from helper_functions import unzip_data ,create_tensorboard_callback, plot_loss_curves, compare_historys

In [ ]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
unzip_data("nlp_getting_started.zip")

--2024-09-24 14:39:01--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 64.233.170.207, 142.251.175.207, 74.125.24.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|64.233.170.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K   698KB/s    in 0.8s    

2024-09-24 14:39:02 (698 KB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



In [ ]:
import pandas as pd

train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
train_df["text"][0]

'Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all'

In [ ]:
#shuffle training dataframe

train_df_shuffled = train_df.sample(frac=1, random_state=42)
train_df_shuffled.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [ ]:
#test dataframe

test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [ ]:
train_df["target"].value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [ ]:
len(train_df), len(test_df)

(7613, 3263)

In [ ]:
#vizualize random training samples

import random

random_index = random.randint(0, len(train_df)-5)
for row in train_df_shuffled[["text", "target"]][random_index:random_index+5].itertuples():
    _, text, target = row

    print(f"Target: {target}", "(real disaster)" if target > 0 else "(not real disaster)")
    print(f"Text:\n{text}\n")
    print("---\n")

Target: 1 (real disaster)
Text:
@EPCOTExplorer my jealous tears are burning with the fire of a thousand ransacked buildings. SO AWESOMEEEEEEEE

---

Target: 1 (real disaster)
Text:
SYD traffic HAZARD Oil spill - BANKSTOWN Stacey St at Wattle St http://t.co/TZyHdBW9f5

---

Target: 0 (not real disaster)
Text:
Are Users of this Sub to be Quarantined? http://t.co/9nLY2TovUD

---

Target: 1 (real disaster)
Text:
@eyecuts @Erasuterism I love 96 Gal Deco to death even if it's a bit trickier to be great with. Glad more weapons are getting Splash Wall

---

Target: 0 (not real disaster)
Text:
Emergency Response and Hazardous Chemical Management: Principles and Practices http://t.co/4sSuyhkgRB http://t.co/TDerBtgZ2k

---



In [ ]:
#split data into training and validation sets

from sklearn.model_selection import train_test_split

train_sentences, val_sentences, train_labels, val_labels = train_test_split(train_df_shuffled["text"].to_numpy(),
                                                                            train_df_shuffled["target"].to_numpy(),
                                                                            test_size=0.1, random_state=42)

In [ ]:
train_sentences.shape, train_labels.shape, val_sentences.shape, val_labels.shape

((6851,), (6851,), (762,), (762,))

In [ ]:
train_sentences[:10], train_labels[:10]

(array(['@mogacola @zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
        "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
        'Somehow find you and I collide http://t.co/Ee8RpOahPk',
        '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
        '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
        'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
       dtype=object),
 array([0,

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization

In [ ]:
text_vectorizer = TextVectorization(max_tokens=None,
                                    standardize="lower_and_strip_punctuation",
                                    split="whitespace",
                                    ngrams=None,
                                    output_mode="int",
                                    output_sequence_length=None,
                                    )

In [ ]:
round(sum([len(i.split()) for i in train_sentences])/len(train_sentences))

15

In [ ]:
max_vocab_length = 10000
max_length = 15

text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                    output_mode="int",
                                    output_sequence_length=max_length)

In [ ]:
text_vectorizer.adapt(train_sentences)

In [ ]:
sample_sentence = ["This is a sample"]
text_vectorizer(sample_sentence)

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[  19,    9,    3, 8839,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0]])>

In [ ]:
random_sentence = random.choice(train_sentences)
print(f"Original text:\n{random_sentence}\
        \n\nVectorized version:")
text_vectorizer([random_sentence])

Original text:
@MartynWaites It's a well-known fact that the St Valentine's Day massacre could have been avoided with some 'oompah-period' Tom Waits.        

Vectorized version:


<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[   1,   37,    3, 6848, 1211,   16,    2,  527, 7088,  101,  344,
         137,   24,   59, 6150]])>

In [ ]:
words_in_vocab = text_vectorizer.get_vocabulary()
top_5_words = words_in_vocab[:5]
bottom_5_words = words_in_vocab[-5:]
print(f"Number of words in vocab: {len(words_in_vocab)}")
print(f"Top 5 most common words: {top_5_words}")
print(f"Bottom 5 least common words: {bottom_5_words}")

Number of words in vocab: 10000
Top 5 most common words: ['', '[UNK]', 'the', 'a', 'in']
Bottom 5 least common words: ['pages', 'paeds', 'pads', 'padres', 'paddytomlinson1']


In [ ]:
#creating embedding

from tensorflow.keras import layers

embedding = layers.Embedding(input_dim=max_vocab_length,
                             output_dim=128,
                             embeddings_initializer="uniform",
                             input_length=max_length,
                             name="embedding_1")

embedding

In [ ]:
random_sentence = random.choice(train_sentences)
print(f"Original text:\n{random_sentence}\
        \n\nEmbedded version:")

sample_embed = embedding(text_vectorizer([random_sentence]))
sample_embed

Original text:
New on Ebay UK Star Wars Storm Trooper Pop! Vinyl Bobble Head Figure POP Funko http://t.co/KJbXIeypma http://t.co/ENPjCfMa8L        

Embedded version:


<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[-0.04772674,  0.0404014 , -0.01235435, ..., -0.02640504,
         -0.02115773, -0.0105919 ],
        [ 0.00779634, -0.01268787,  0.03658802, ..., -0.02098591,
          0.02055338,  0.03380264],
        [-0.03061306,  0.04672779,  0.02066103, ..., -0.02710146,
         -0.00899006, -0.01713942],
        ...,
        [-0.02151233, -0.0046928 , -0.01701465, ...,  0.00920611,
          0.01911937,  0.0068556 ],
        [ 0.04496156, -0.02676236, -0.02160413, ...,  0.04013186,
         -0.00996421,  0.04322896],
        [-0.02151233, -0.0046928 , -0.01701465, ...,  0.00920611,
          0.01911937,  0.0068556 ]]], dtype=float32)>

In [ ]:
sample_embed[0][0][:]

<tf.Tensor: shape=(128,), dtype=float32, numpy=
array([-0.04772674,  0.0404014 , -0.01235435, -0.00355822, -0.03778832,
       -0.04662362, -0.03098856, -0.01720804,  0.02882058,  0.04574114,
       -0.01419495,  0.03345542, -0.03590361,  0.02724857, -0.01474929,
       -0.00834975, -0.04852515, -0.02766407, -0.022662  , -0.04868566,
       -0.04486094, -0.03663603,  0.028912  , -0.0378686 ,  0.0406889 ,
       -0.0108784 , -0.03993801,  0.03298788, -0.02503709, -0.02499764,
        0.0493666 ,  0.04205686, -0.00143499, -0.03776349,  0.00855043,
        0.03644986, -0.02684276, -0.04878881,  0.01325483, -0.01099039,
        0.01525963, -0.04537094,  0.00243343, -0.04157765,  0.03318968,
       -0.01155645,  0.01701577,  0.01616594, -0.01420951, -0.01017775,
        0.04197898, -0.03243299, -0.0345429 ,  0.04215235,  0.04930637,
       -0.00723137,  0.01072512, -0.02206458, -0.02722936,  0.02982031,
       -0.00248722,  0.00840326,  0.0469701 , -0.02014973,  0.04111249,
        0.029341

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

model_0 = Pipeline([
                    ("tfidf", TfidfVectorizer()),
                    ("clf", MultinomialNB())
])

model_0.fit(train_sentences, train_labels)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [ ]:
baseline_score = model_0.score(val_sentences, val_labels)
print(f"Our baseline model achieves an accuracy of: {baseline_score*100:.2f}%")

Our baseline model achieves an accuracy of: 79.27%


In [ ]:
baseline_preds = model_0.predict(val_sentences)
baseline_preds[:20]

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1])

In [ ]:
val_labels[:20]

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [ ]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results(y_true, y_pred):
    model_accuracy = accuracy_score(y_true, y_pred) * 100

    model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average="weighted")
    model_results = {"accuracy": model_accuracy,
                     "precision": model_precision,
                     "recall": model_recall,
                     "f1": model_f1}
    return model_results

In [ ]:
baseline_results = calculate_results(y_true=val_labels,
                                    y_pred=baseline_preds)
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

In [ ]:
#DL for text classification

from tensorflow.keras import layers

inputs = layers.Input(shape=(1,), dtype=tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
x = layers.GlobalMaxPooling1D()(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_1 = tf.keras.Model(inputs, outputs, name="model_1_dense")

In [ ]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding_1 (Embedding)     (None, 15, 128)           1280000   
                                                                 
 global_max_pooling1d (Glob  (None, 128)               0         
 alMaxPooling1D)                                                 
                                                                 
 dense (Dense)               (None, 1)                 129       
                                                                 
Total params: 1280129 (4.88 MB)
Trainable params: 128

In [ ]:
 model_1.compile(loss="binary_crossentropy",
                 optimizer=tf.keras.optimizers.Adam(),
                 metrics=["accuracy"])

In [ ]:
model_1_history = model_1.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels)
                              )

Epoch 1/5
215/215 [==============================] - 17s 57ms/step - loss: 0.6388 - accuracy: 0.6444 - val_loss: 0.5749 - val_accuracy: 0.7585
Epoch 2/5
215/215 [==============================] - 2s 11ms/step - loss: 0.4701 - accuracy: 0.8251 - val_loss: 0.4765 - val_accuracy: 0.7848
Epoch 3/5
215/215 [==============================] - 2s 11ms/step - loss: 0.3435 - accuracy: 0.8751 - val_loss: 0.4530 - val_accuracy: 0.7848
Epoch 4/5
215/215 [==============================] - 1s 5ms/step - loss: 0.2598 - accuracy: 0.9057 - val_loss: 0.4579 - val_accuracy: 0.7835
Epoch 5/5
215/215 [==============================] - 1s 5ms/step - loss: 0.1989 - accuracy: 0.9334 - val_loss: 0.4714 - val_accuracy: 0.7861


In [ ]:
model_1.evaluate(val_sentences, val_labels)

24/24 [==============================] - 0s 3ms/step - loss: 0.4714 - accuracy: 0.7861


[0.471443235874176, 0.7860892415046692]

In [ ]:
model_1_pred_probs = model_1.predict(val_sentences)
model_1_pred_probs.shape, model_1_pred_probs[:10]

24/24 [==============================] - 0s 2ms/step


((762, 1),
 array([[0.30504483],
        [0.88167495],
        [0.9928266 ],
        [0.05186204],
        [0.25504   ],
        [0.9642682 ],
        [0.9271693 ],
        [0.9868836 ],
        [0.9334982 ],
        [0.08581804]], dtype=float32))

In [ ]:
model_1_preds = tf.squeeze(tf.round(model_1_pred_probs))
model_1_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0.], dtype=float32)>

In [ ]:
val_labels[:10]

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0])

In [ ]:
model_1_results = calculate_results(y_true=val_labels,
                                    y_pred=model_1_preds)
model_1_results

{'accuracy': 78.60892388451444,
 'precision': 0.7920916944370863,
 'recall': 0.7860892388451444,
 'f1': 0.7827032509906072}

In [ ]:
import numpy as np

np.array(list(model_1_results.values())) >= np.array(list(baseline_results.values()))

array([False, False, False, False])

In [ ]:
words_in_vocab = text_vectorizer.get_vocabulary()
len(words_in_vocab), words_in_vocab[:10]

(10000, ['', '[UNK]', 'the', 'a', 'in', 'to', 'of', 'and', 'i', 'is'])

In [ ]:
model_1.layers

In [ ]:
embed_weights = model_1.get_layer("embedding_1").get_weights()[0]
embed_weights.shape

(10000, 128)

In [ ]:
import io

out_v = io.open("embedding_vectors.tsv", "w", encoding="utf-8")
out_m = io.open("embedding_metadata.tsv", "w", encoding="utf-8")

for index, word in enumerate(words_in_vocab):
    if index == 0:
        continue
    vec = embed_weights[index]
    out_v.write("\t".join([str(x) for x in vec]) + "\n")
    out_m.write(word + "\n")
out_v.close()
out_m.close()

In [ ]:
try:
    from google.colab import files
except ImportError:
    pass
else:
    files.download("embedding_vectors.tsv")
    files.download("embedding_metadata.tsv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
from tensorflow.keras import layers

inputs = layers.Input(shape=(1,), dtype=tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
# print(x.shape)
x = layers.LSTM(256, return_sequences=True)(x)
x = layers.LSTM(128, return_sequences=True)(x)
x = layers.LSTM(64, return_sequences=True)(x)
x = layers.LSTM(32, return_sequences=True)(x)
x = layers.LSTM(64, return_sequences=True)(x)
x = layers.LSTM(128, return_sequences=True)(x)
# print(x.shape)
x = layers.LSTM(256)(x)
# print(x.shape)
# x = layers.Dense(128, activation="relu")(x)
# x = layers.Dense(64, activation="relu")(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_2 = tf.keras.Model(inputs, outputs, name="model_2_LSTM")

In [ ]:
model_2.summary()

Model: "model_2_LSTM"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding_1 (Embedding)     (None, 15, 128)           1280000   
                                                                 
 lstm (LSTM)                 (None, 15, 256)           394240    
                                                                 
 lstm_1 (LSTM)               (None, 15, 128)           197120    
                                                                 
 lstm_2 (LSTM)               (None, 15, 64)            49408     
                                                      

In [ ]:
model_2.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [ ]:
model_2_history = model_2.fit(train_sentences,
                              train_labels,
                              epochs=10,
                              validation_data=(val_sentences, val_labels))
#

Epoch 1/10
215/215 [==============================] - 25s 59ms/step - loss: 0.3930 - accuracy: 0.8339 - val_loss: 0.4707 - val_accuracy: 0.7835
Epoch 2/10
215/215 [==============================] - 6s 30ms/step - loss: 0.2671 - accuracy: 0.8945 - val_loss: 0.5108 - val_accuracy: 0.7822
Epoch 3/10
215/215 [==============================] - 6s 27ms/step - loss: 0.1904 - accuracy: 0.9340 - val_loss: 0.6846 - val_accuracy: 0.7677
Epoch 4/10
215/215 [==============================] - 5s 22ms/step - loss: 0.1420 - accuracy: 0.9492 - val_loss: 0.6981 - val_accuracy: 0.7756
Epoch 5/10
215/215 [==============================] - 5s 21ms/step - loss: 0.1177 - accuracy: 0.9580 - val_loss: 0.9395 - val_accuracy: 0.7585
Epoch 6/10
215/215 [==============================] - 4s 20ms/step - loss: 0.0931 - accuracy: 0.9660 - val_loss: 0.7332 - val_accuracy: 0.7638
Epoch 7/10
215/215 [==============================] - 4s 18ms/step - loss: 0.0793 - accuracy: 0.9699 - val_loss: 0.8211 - val_accuracy: 0.752

In [ ]:
model_2_pred_probs = model_2.predict(val_sentences)
model_2_pred_probs.shape, model_2_pred_probs[:10]

24/24 [==============================] - 2s 8ms/step


((762, 1),
 array([[3.4901269e-02],
        [8.2132918e-01],
        [9.9974579e-01],
        [2.0001450e-01],
        [3.0451949e-04],
        [9.9990869e-01],
        [9.6470660e-01],
        [9.9991930e-01],
        [9.9989080e-01],
        [1.8600015e-02]], dtype=float32))

In [ ]:
model_2_preds = tf.squeeze(tf.round(model_2_pred_probs))
model_2_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0.], dtype=float32)>

In [ ]:
model_2_results = calculate_results(y_true=val_labels,
                                    y_pred=model_2_preds)
model_2_results

{'accuracy': 76.11548556430446,
 'precision': 0.7642332843987721,
 'recall': 0.7611548556430446,
 'f1': 0.7581159886309101}

In [ ]:
from ast import Global
from tensorflow.keras import layers

inputs = layers.Input(shape=(1,), dtype=tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
x = layers.GRU(64)(x)
# x = layers.LSTM(64, return_sequences=True)(x)
# x = layers.GRU(64)(x)
# x = layers.Dense(64, activation="relu")(x)

outputs = layers.Dense(1, activation="sigmoid")(x)

model_3 = tf.keras.Model(inputs, outputs, name="model_3_GRU")

In [ ]:
model_3.summary()

Model: "model_3_GRU"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding_1 (Embedding)     (None, 15, 128)           1280000   
                                                                 
 gru (GRU)                   (None, 64)                37248     
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 1317313 (5.03 MB)
Trainable params: 1317313 (5.03 MB)
Non-trainable params: 0 (0.00 Byte)
_________________

In [ ]:
model_3.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [ ]:
model_3.history = model_3.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 10s 32ms/step - loss: 0.1971 - accuracy: 0.9228 - val_loss: 0.7085 - val_accuracy: 0.7638
Epoch 2/5
215/215 [==============================] - 3s 13ms/step - loss: 0.0903 - accuracy: 0.9667 - val_loss: 0.9534 - val_accuracy: 0.7717
Epoch 3/5
215/215 [==============================] - 2s 12ms/step - loss: 0.0687 - accuracy: 0.9758 - val_loss: 0.8260 - val_accuracy: 0.7690
Epoch 4/5
215/215 [==============================] - 2s 10ms/step - loss: 0.0474 - accuracy: 0.9777 - val_loss: 1.0850 - val_accuracy: 0.7612
Epoch 5/5
215/215 [==============================] - 2s 7ms/step - loss: 0.0449 - accuracy: 0.9791 - val_loss: 1.2520 - val_accuracy: 0.7493


In [ ]:
model_3_pred_probs = model_3.predict(val_sentences)
model_3_pred_probs.shape, model_3_pred_probs[:10]

24/24 [==============================] - 0s 4ms/step


((762, 1),
 array([[2.8376821e-03],
        [7.8693342e-01],
        [9.9989390e-01],
        [2.3582043e-01],
        [4.3743491e-04],
        [9.9991322e-01],
        [9.9795234e-01],
        [9.9994457e-01],
        [9.9994302e-01],
        [4.2206791e-01]], dtype=float32))

In [ ]:
model_3_preds = tf.squeeze(tf.round(model_3_pred_probs))
model_3_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0.], dtype=float32)>

In [ ]:
model_3_results = calculate_results(y_true=val_labels,
                                    y_pred=model_3_preds)
model_3_results

{'accuracy': 74.93438320209974,
 'precision': 0.7488957031272704,
 'recall': 0.7493438320209974,
 'f1': 0.7485447240178604}

In [ ]:
from tensorflow.keras import layers

inputs = layers.Input(shape=(1,), dtype=tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
x = layers.Bidirectional(layers.GRU(64, return_sequences=True))(x)
x = layers.Bidirectional(layers.GRU(64))(x)
outputs = layers.Dense(1, activation="sigmoid")(x)

model_4 = tf.keras.Model(inputs, outputs, name="model_4_Bidirectional_GRU")

In [ ]:
model_4.summary()

Model: "model_4_Bidirectional_GRU"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 1)]               0         
                                                                 
 text_vectorization_1 (Text  (None, 15)                0         
 Vectorization)                                                  
                                                                 
 embedding_1 (Embedding)     (None, 15, 128)           1280000   
                                                                 
 bidirectional (Bidirection  (None, 15, 128)           74496     
 al)                                                             
                                                                 
 bidirectional_1 (Bidirecti  (None, 128)               74496     
 onal)                                                           
                                         

In [ ]:
model_4.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [ ]:
model_4_history = model_4.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 18s 47ms/step - loss: 0.1273 - accuracy: 0.9480 - val_loss: 1.0128 - val_accuracy: 0.7651
Epoch 2/5
215/215 [==============================] - 4s 18ms/step - loss: 0.0700 - accuracy: 0.9737 - val_loss: 0.9482 - val_accuracy: 0.7507
Epoch 3/5
215/215 [==============================] - 3s 12ms/step - loss: 0.0472 - accuracy: 0.9783 - val_loss: 1.3932 - val_accuracy: 0.7625
Epoch 4/5
215/215 [==============================] - 3s 12ms/step - loss: 0.0424 - accuracy: 0.9797 - val_loss: 1.3673 - val_accuracy: 0.7572
Epoch 5/5
215/215 [==============================] - 3s 14ms/step - loss: 0.0388 - accuracy: 0.9801 - val_loss: 1.4808 - val_accuracy: 0.7677


In [ ]:
model_4_pred_probs = model_4.predict(val_sentences)
model_4_pred_probs.shape, model_4_pred_probs[:10]

24/24 [==============================] - 1s 4ms/step


((762, 1),
 array([[2.2651989e-04],
        [7.7865201e-01],
        [9.9988198e-01],
        [1.8910952e-01],
        [1.1552882e-04],
        [9.9976653e-01],
        [9.9964845e-01],
        [9.9995053e-01],
        [9.9995089e-01],
        [1.1374879e-01]], dtype=float32))

In [ ]:
model_4_preds = tf.squeeze(tf.round(model_4_pred_probs))
model_4_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0.], dtype=float32)>

In [ ]:
model_4_results = calculate_results(y_true=val_labels,
                                    y_pred=model_4_preds)
model_4_results

{'accuracy': 76.77165354330708,
 'precision': 0.7675450859410361,
 'recall': 0.7677165354330708,
 'f1': 0.7667932666650167}

In [ ]:
#use convolutional layers

In [ ]:
embedding_test = embedding(text_vectorizer(["This is a test sentence"]))
conv_1d = layers.Conv1D(filters=32, kernel_size=5, activation="relu", padding="valid")
conv_1d_output = conv_1d(embedding_test)
max_pool = layers.GlobalMaxPool1D()
max_pool_output = max_pool(conv_1d_output)
embedding_test.shape, conv_1d_output.shape, max_pool_output.shape

embedding_test.shape, conv_1d_output.shape, max_pool_output.shape

(TensorShape([1, 15, 128]), TensorShape([1, 11, 32]), TensorShape([1, 32]))

In [ ]:
from tensorflow.keras import layers

inoputs = layers.Input(shape=(1,), dtype=tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
x = layers.Conv1D(filters=64, kernel_size=5, activation="relu")(x)
x = layers.GlobalMaxPool1D()(x)
outputs = layers.Dense(1, activation="sigmoid")(x)

model_5 = tf.keras.Model(inputs, outputs, name="model_5_Conv1D")

In [ ]:
model_5.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [ ]:
model_5_history = model_5.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 11s 44ms/step - loss: 0.1469 - accuracy: 0.9534 - val_loss: 0.8543 - val_accuracy: 0.7493
Epoch 2/5
215/215 [==============================] - 2s 10ms/step - loss: 0.0707 - accuracy: 0.9749 - val_loss: 1.0067 - val_accuracy: 0.7585
Epoch 3/5
215/215 [==============================] - 1s 7ms/step - loss: 0.0591 - accuracy: 0.9784 - val_loss: 1.0641 - val_accuracy: 0.7559
Epoch 4/5
215/215 [==============================] - 2s 8ms/step - loss: 0.0509 - accuracy: 0.9804 - val_loss: 1.1060 - val_accuracy: 0.7507
Epoch 5/5
215/215 [==============================] - 2s 10ms/step - loss: 0.0492 - accuracy: 0.9799 - val_loss: 1.1278 - val_accuracy: 0.7572


In [ ]:
model_5_pred_probs = model_5.predict(val_sentences)
model_5_pred_probs.shape, model_5_pred_probs[:10]

24/24 [==============================] - 0s 3ms/step


((762, 1),
 array([[9.0515658e-02],
        [7.2342128e-01],
        [9.9984694e-01],
        [1.3544802e-01],
        [1.4381475e-05],
        [9.6910763e-01],
        [9.8121613e-01],
        [9.9968135e-01],
        [9.9999857e-01],
        [2.7445331e-01]], dtype=float32))

In [ ]:
model_5_preds = tf.squeeze(tf.round(model_5_pred_probs))
model_5_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0.], dtype=float32)>

In [ ]:
model_5_results = calculate_results(y_true=val_labels,
                                    y_pred=model_5_preds)
model_5_results

{'accuracy': 75.7217847769029,
 'precision': 0.7574646046920478,
 'recall': 0.7572178477690289,
 'f1': 0.7557133417830909}

In [ ]:
sample_sentence = "There's a flood in my street!"

In [ ]:
import tensorflow_hub as hub

embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
embed_samples = embed([sample_sentence,
                       "When you can the universal sentence encoder on a sentence, it turns it into numbers."])
print(embed_samples[0].shape)

(512,)


In [ ]:
embed_samples.shape

TensorShape([2, 512])

In [ ]:
sentence_encorder_layer = hub.KerasLayer("https://tfhub.dev/google/universal-sentence-encoder/4",
                                        input_shape=[],
                                        dtype=tf.string,
                                        trainable =False,
                                        name="USE")

In [ ]:
model_6 = tf.keras.Sequential([
    sentence_encorder_layer,
    layers.Dense(64, activation="relu"),
    layers.Dense(64, activation="relu"),
    layers.Dense(1, activation="sigmoid")
], name="model_6_USE")

In [ ]:
model_6.summary()

Model: "model_6_USE"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 USE (KerasLayer)            (None, 512)               256797824 
                                                                 
 dense_5 (Dense)             (None, 64)                32832     
                                                                 
 dense_6 (Dense)             (None, 64)                4160      
                                                                 
 dense_7 (Dense)             (None, 1)                 65        
                                                                 
Total params: 256834881 (979.75 MB)
Trainable params: 37057 (144.75 KB)
Non-trainable params: 256797824 (979.61 MB)
_________________________________________________________________


In [ ]:
model_6.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

model_6_history = model_6.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 6s 14ms/step - loss: 0.4845 - accuracy: 0.7888 - val_loss: 0.4356 - val_accuracy: 0.8058
Epoch 2/5
215/215 [==============================] - 3s 15ms/step - loss: 0.4008 - accuracy: 0.8260 - val_loss: 0.4239 - val_accuracy: 0.8163
Epoch 3/5
215/215 [==============================] - 3s 15ms/step - loss: 0.3801 - accuracy: 0.8339 - val_loss: 0.4238 - val_accuracy: 0.8189
Epoch 4/5
215/215 [==============================] - 3s 13ms/step - loss: 0.3594 - accuracy: 0.8475 - val_loss: 0.4137 - val_accuracy: 0.8241
Epoch 5/5
215/215 [==============================] - 3s 12ms/step - loss: 0.3341 - accuracy: 0.8612 - val_loss: 0.4281 - val_accuracy: 0.8281


In [ ]:
model_6_pred_probs = model_6.predict(val_sentences)
model_6_pred_probs[:10]

24/24 [==============================] - 1s 9ms/step


array([[0.10258281],
       [0.9176057 ],
       [0.99841666],
       [0.26165256],
       [0.61523145],
       [0.91795695],
       [0.9829852 ],
       [0.99627846],
       [0.9886646 ],
       [0.12186954]], dtype=float32)

In [ ]:
model_6_preds = tf.squeeze(tf.round(model_6_pred_probs))
model_6_preds[:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 1., 1., 0., 1., 1., 1., 1., 1., 0.], dtype=float32)>

In [ ]:
model_6_results = calculate_results(y_true=val_labels,
                                    y_pred=model_6_preds)
model_6_results

{'accuracy': 82.80839895013123,
 'precision': 0.8317661082254704,
 'recall': 0.8280839895013123,
 'f1': 0.826376703141215}

In [ ]:
train_10_precent_split = int(0.1 * len(train_sentences))
train_sentences_10_precent = train_sentences[:train_10_precent_split]
train_labels_10_precent    = train_labels[:train_10_precent_split]

In [ ]:
# One kind of correct way (there are more) to make data subset
# (split the already split train_sentences/train_labels)
train_sentences_90_percent, train_sentences_10_percent, train_labels_90_percent, train_labels_10_percent = train_test_split(np.array(train_sentences),
                                                                                                                            train_labels,
                                                                                                                            test_size=0.1,
                                                                                                                            random_state=42)

In [ ]:
# Clone model_6
model_7 = tf.keras.models.clone_model(model_6)

# Set the new name for model_7
model_7._name = "model_7_10_percent"


In [ ]:
model_7.summary()

Model: "model_7_10_percent"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 USE (KerasLayer)            (None, 512)               256797824 
                                                                 
 dense_5 (Dense)             (None, 64)                32832     
                                                                 
 dense_6 (Dense)             (None, 64)                4160      
                                                                 
 dense_7 (Dense)             (None, 1)                 65        
                                                                 
Total params: 256834881 (979.75 MB)
Trainable params: 37057 (144.75 KB)
Non-trainable params: 256797824 (979.61 MB)
_________________________________________________________________


In [ ]:
model_7.compile(loss="binary_crossentropy",
              optimizer=tf.keras.optimizers.Adam(),
              metrics=["accuracy"])

model_7_history = model_7.fit(train_sentences_10_percent,
                              train_labels_10_percent,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
22/22 [==============================] - 4s 45ms/step - loss: 0.6751 - accuracy: 0.6079 - val_loss: 0.6641 - val_accuracy: 0.5722
Epoch 2/5
22/22 [==============================] - 0s 23ms/step - loss: 0.6037 - accuracy: 0.7012 - val_loss: 0.5953 - val_accuracy: 0.7100
Epoch 3/5
22/22 [==============================] - 0s 23ms/step - loss: 0.4888 - accuracy: 0.8309 - val_loss: 0.5205 - val_accuracy: 0.7730
Epoch 4/5
22/22 [==============================] - 0s 23ms/step - loss: 0.3897 - accuracy: 0.8440 - val_loss: 0.4874 - val_accuracy: 0.7874
Epoch 5/5
22/22 [==============================] - 0s 22ms/step - loss: 0.3263 - accuracy: 0.8659 - val_loss: 0.4839 - val_accuracy: 0.7835


In [ ]:
model_7.layers[0]

In [ ]:
model_6.save("model_6_h5.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
import tensorflow_hub as hub

loaded_model_6 = tf.keras.models.load_model("model_6_h5.h5",
                                             custom_objects={"KerasLayer": hub.KerasLayer})

In [ ]:
model_6.save("model_6.keras")

In [ ]:
loaded_model_6_keras = tf.keras.models.load_model("model_6.keras", custom_objects={"KerasLayer": hub.KerasLayer})

In [ ]:
model_6.save("model_6_savemodel_format")

In [ ]:
loaded_model_6_savedmodel = tf.keras.models.load_model("model_6_savemodel_format")

In [ ]:
!wget https://storage.googleapis.com/ztm_tf_course/08_model_6_USE_feature_extractor.zip
!unzip 08_model_6_USE_feature_extractor.zip

--2024-09-24 14:45:56--  https://storage.googleapis.com/ztm_tf_course/08_model_6_USE_feature_extractor.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 172.253.118.207, 74.125.200.207, 74.125.130.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.253.118.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 960779165 (916M) [application/zip]
Saving to: ‘08_model_6_USE_feature_extractor.zip’

08_model_6_USE_feat 100%[===================>] 916.27M  19.4MB/s    in 47s     

2024-09-24 14:46:44 (19.5 MB/s) - ‘08_model_6_USE_feature_extractor.zip’ saved [960779165/960779165]

Archive:  08_model_6_USE_feature_extractor.zip
   creating: 08_model_6_USE_feature_extractor/
   creating: 08_model_6_USE_feature_extractor/assets/
   creating: 08_model_6_USE_feature_extractor/variables/
  inflating: 08_model_6_USE_feature_extractor/variables/variables.data-00000-of-00001  
  inflating: 08_model_6_USE_feature_extractor/variables/variables

In [ ]:
model_6_pretrained = tf.keras.models.load_model("08_model_6_USE_feature_extractor")

In [ ]:
model_6_pretrained_pred_probs = model_6_pretrained.predict(val_sentences)
model_6_pretrained_pred = tf.squeeze(tf.round(model_6_pretrained_pred_probs))
model_6_pretrained_results = calculate_results(y_true=val_labels,
                                               y_pred=model_6_pretrained_pred)
model_6_pretrained_results

24/24 [==============================] - 0s 17ms/step


{'accuracy': 81.62729658792651,
 'precision': 0.818446310697231,
 'recall': 0.8162729658792651,
 'f1': 0.8148082644367335}

In [ ]:
val_df = pd.DataFrame({"text":val_sentences,
                       "target":val_labels,
                       "pred":model_6_pretrained_pred,
                       "probs":tf.squeeze(model_6_pretrained_pred_probs)})

val_df.head()

text  target  pred     probs
0  DFR EP016 Monthly Meltdown - On Dnbheaven 2015...       0   0.0  0.159757
1  FedEx no longer to transport bioterror germs i...       0   1.0  0.747162
2  Gunmen kill four in El Salvador bus attack: Su...       1   1.0  0.988749
3  @camilacabello97 Internally and externally scr...       1   0.0  0.196229
4  Radiation emergency #preparedness starts with ...       1   1.0  0.707808

In [ ]:
most_wrong = val_df[val_df["target"] != val_df["pred"]].sort_values("probs", ascending = False)
most_wrong

text  target  pred     probs
31   ? High Skies - Burning Buildings ? http://t.co...       0   1.0  0.910196
759  FedEx will no longer transport bioterror patho...       0   1.0  0.876982
628  @noah_anyname That's where the concentration c...       0   1.0  0.852300
209  Ashes 2015: Australia‰Ûªs collapse at Trent Br...       0   1.0  0.835454
251  @AshGhebranious civil rights continued in the ...       0   1.0  0.827213
..                                                 ...     ...   ...       ...
411  @SoonerMagic_ I mean I'm a fan but I don't nee...       1   0.0  0.043919
233                    I get to smoke my shit in peace       1   0.0  0.042087
38   Why are you deluged with low self-image? Take ...       1   0.0  0.038998
244  Reddit Will Now Quarantine‰Û_ http://t.co/pkUA...       1   0.0  0.038949
23   Ron &amp; Fez - Dave's High School Crush https...       1   0.0  0.037186

[140 rows x 4 columns]

In [ ]:
for row in most_wrong[:10].itertuples():
  _, text, target, pred, probs = row
  print(f"Target: {target}, pred: {pred}, prob: {probs}")
  print(f"Text:\n{text}\n")
  print("----\n")

Target: 0, pred: 1.0, prob: 0.9101957678794861
Text:
? High Skies - Burning Buildings ? http://t.co/uVq41i3Kx2 #nowplaying

----

Target: 0, pred: 1.0, prob: 0.8769821524620056
Text:
FedEx will no longer transport bioterror pathogens in wake of anthrax lab mishaps http://t.co/lHpgxc4b8J

----

Target: 0, pred: 1.0, prob: 0.8523001074790955
Text:
@noah_anyname That's where the concentration camps and mass murder come in. 
 
EVERY. FUCKING. TIME.

----

Target: 0, pred: 1.0, prob: 0.8354544043540955
Text:
Ashes 2015: Australia‰Ûªs collapse at Trent Bridge among worst in history: England bundled out Australia for 60 ... http://t.co/t5TrhjUAU0

----

Target: 0, pred: 1.0, prob: 0.8272132873535156
Text:
@AshGhebranious civil rights continued in the 60s. And what about trans-generational trauma? if anything we should listen to the Americans.

----

Target: 0, pred: 1.0, prob: 0.814815878868103
Text:
@SonofLiberty357 all illuminated by the brightly burning buildings all around the town!

----

In [ ]:
test_sentences = test_df["text"].to_list()
test_samples = random.sample(test_sentences, 10)

for test_sample in test_samples:
  pred_prob = tf.squeeze(model_6_pretrained.predict([test_sample]))
  pred = tf.round(pred_prob)
  print(f"pred: {int(pred)} prob: {pred_prob}")
  print(f"Text: {test_sample}")
  print("-----")

1/1 [==============================] - 0s 62ms/step
pred: 0 prob: 0.14530079066753387
Text: Do people not understand they cant bleeding tweet everyone all the timedoes me head in 'stop ignoring me' they are hardly ignoring you+
-----
1/1 [==============================] - 0s 63ms/step
pred: 0 prob: 0.30527082085609436
Text: Brass and Copper in Cataclysm &amp; AfterShock!!! http://t.co/uxYZyaygTy
-----
1/1 [==============================] - 0s 60ms/step
pred: 0 prob: 0.08645450323820114
Text: Crackdown 3 Destruction Restricted To Multiplayer; Co-Developed By Sumo Digital: Crackdown 3 åÊwas definitely o... http://t.co/O4B1KIyx1P
-----
1/1 [==============================] - 0s 87ms/step
pred: 0 prob: 0.0708228349685669
Text: When God pushes you to the edge of the cliff two things may happen:
1) He will catch you when you fall.
2) He will teach you how to fly.
-----
1/1 [==============================] - 0s 56ms/step
pred: 0 prob: 0.21356827020645142
Text: People are finally panicking abou

In [ ]:
test_text = "burning houses is near"

tets_pred = model_6_pretrained.predict([test_text])
tets_pred

1/1 [==============================] - 0s 37ms/step


array([[0.6315224]], dtype=float32)